### PR TITLE
Send attachment with mail

### LINKED ISSUE #90: send email with attachments
I'd like to send an email with an attachment but it is unclear how to do so.

Here's a fragment from [OutlookTests](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/test/java/com/microsoft/graph/functional/OutlookTests.java):

```java
Message message = new Message();
message.subject = "Test E-Mail";
...
// how do i set attachments?
message.attachments = new AttachmentCollectionPage(response??, builder??);
// now add the attachments to the page
...
testBase.graphClient.me().sendMail(message, true).buildRequest().post();
```

In its current state the `AttachmentCollectionPage` object seems read-focused. How do I use it for write (or is this the wrong approach)?

### LINKED ISSUE #192: Not able to send attachment with this API https://graph.microsoft.com/v1.0/me/sendMail
Getting 400 Bad Request with error body : "Property attachments in payload has a value that does not match schema."

Trying to upload the attachment as shown below where message is initialized as 
Message message = new Message(); 
and filled other message values like subject, body etc. It is working fine without attachment upload.

final BaseAttachmentCollectionResponse response = new BaseAttachmentCollectionResponse();
        try {
            response.value = Arrays.asList(getFileAttachment());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        message.attachments = new AttachmentCollectionPage(response, null);
       
    }
  
    private FileAttachment getFileAttachment() throws Exception{
        FileAttachment fileAttachment = new FileAttachment();
        fileAttachment.name = "document.pdf";
        File pdfFile = new File("src/main/resources/document.pdf");
        InputStream fileStream = new FileInputStream(pdfFile);
        fileAttachment.contentBytes = getByteArray(fileStream);
        fileAttachment.oDataType = "#microsoft.graph.fileAttachment";
        return fileAttachment;
}

API used to send the email is : https://graph.microsoft.com/v1.0/me/sendMail
I am not sure where I am doing wrong.

Appreciate your help here..

### PR DESCRIPTION
**Pull request by NakulSabharwal**
Fixes #192 
Fixes #90

### Changes proposed in this pull request
- Serializer for attachments.
- Tests for sending attachment with email.
- Expose attachment attribute

### CODE REVIEW

**Review by baywet — APPROVED** [review]

**Review by MIchaelMainer — APPROVED** [review]
Reviewed online with Vincent

**Comment by Przemek-12** [comment]
Hi, I can't send mail messagewith attachment. I get NoSuchMethodException at CollectionPageSerializer class, line 84. 
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'.
In JsonParser class, there's no parseString method. There's only parse(String json).

**Comment by baywet** [comment]
hi @Przemek-12 
Can you open a separate issue please so it's easier for us to have a focused discussion?
Thanks!

**Comment by Przemek-12** [comment]
hi, just opened it: https://github.com/microsoftgraph/msgraph-sdk-java/issues/515

**Pull request merged**
