### PR TITLE
Generated v1.0 models and request builders using Typewriter

### PR DESCRIPTION
**Pull request by ramsessanchez**
This pull request was automatically created by the GitHub Action, **create pull request**. 

 The commit hash is _2a8956a94940ad33e847b8a7616f3319d6b24331_. 

 **Important** Check for unexpected deletions or changes in this PR.

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
@ramsessanchez to investigate why this one is failing

**Review by baywet — CHANGES_REQUESTED** [review]
I think we should close this one, it shows no actual changes, which is a bit weird considering we had a breaking change. (maybe a regression from another fix?)

**Comment by ramsessanchez** [comment]
@baywet yeah, this is strange, Im having trouble running pkg diff locally to verify, but as far as I can tell from the github comparison I only notice namespace and comment changes.

**Comment by ramsessanchez** [comment]
@baywet, Actually I know what happened. Last week with the generation fix I did work to remove a lot of unnecessary import statements. I believe I deleted a few import statements that belonged in different namespaces so this time around it had trouble finding those properties. Todays changes made all properties fully qualified so this should no longer be an issue going forward since a fully qualified namespace removes the need for import statements.

**Pull request closed without merging**
