### PR TITLE
August Updates

### LINKED ISSUE #44: Import wildcards
I'd rank this as a nice to have. 

Import wildcards are used throughout the library. This has two primary effects:

* Namespace disambiguation must be controlled by class names rather than just package names
* Understanding the code outside a java enabled IDE is difficult (say in the browser)

The first one has been dealt with by ensuring no names are repeated between packages and I can cope with that though it is not ideal.

The second point is a more critical annoyance when trying to browse the code on github itself or as text locally because you can't see what package a referenced class is from.

The import wildcards in the generated code can be removed (and ambiguous names handled correctly with full qualification when necessary) using a technique like this (taken from https://github.com/davidmoten/state-machine/blob/master/state-machine-generator/src/main/java/com/github/davidmoten/fsm/model/Generator.java):

```java
Imports imports = new Imports();
ByteArrayOutputStream bytes = new ByteArrayOutputStream();
PrintStream out = new PrintStream(bytes);
out.format("package %s;\n", pkg);
out.println();
out.println("<IMPORTS>");
out.println();
out.format("public interface %s<Id> extends %s<%s, Id>{\n", behaviourClassSimpleName(),
                    imports.add(EntityBehaviour.class), imports.add(clsName));
...
result.print(new String(bytes.toByteArray(StandardCharsets.UTF_8))
            .replace("<IMPORTS>", imports.importsAsString()));
```
In a nutshell, you write your imports last after registering all types in the `Imports` and the `Imports` object decides which classes need to be fully qualified (first in best dressed).

An easy option is after pasting generated code, use an IDE like Eclipse to organize imports across the project (right mouse on project - Source - Organize imports).

Got an opinion on this one @cbales?

### LINKED ISSUE #77: Memory requirements
The addition of InTune classes has pushed the memory requirement to compile the project with gradle to 10GB (on linux). I'm fortunate to have plenty of RAM on my work desktop but this high requirement will preclude me from using gradle on this project on my laptop for instance (which has 8GB).

These high memory requirements will make contributions from the community more difficult.

Might be time to split the project into multiple projects (in this repo)?

### PR DESCRIPTION
**Pull request by deepak2016**
- August generation for Graph updates
- Memory requirement issue fix #77 
- Import wildcards fix #44 
- Delete query ClassCastException fix 850967

Below is the list of pull requests in generator repo:

microsoftgraph/MSGraph-SDK-Code-Generator#133
microsoftgraph/MSGraph-SDK-Code-Generator#135
microsoftgraph/MSGraph-SDK-Code-Generator#136
microsoftgraph/MSGraph-SDK-Code-Generator#137
microsoftgraph/MSGraph-SDK-Code-Generator#138
microsoftgraph/MSGraph-SDK-Code-Generator#139
microsoftgraph/MSGraph-SDK-Code-Generator#140
microsoftgraph/MSGraph-SDK-Code-Generator#145

### CODE REVIEW

**Comment by davidmoten** [comment]
@deepak2016 can you add the issue number to the "memory requirement issue fix" please

**Comment by MIchaelMainer** [comment]
Good catch @davidmoten . It looks like the start imports work has been applied to the /requests and not the /models.

**Comment by deepak2016** [comment]
Yes, have done changes so that SDK builds with less than 2GB RAM. Have not tried to fix everything.
Followed below approach to chose tempalates to fix:
1. Create a list of template file vs number of java files getting generated against that template. 
2. Sort this list based on number of java files generated
3. We ended up fixing ~25-30 templates out of ~80 templates to get maximum impact.

**Comment by davidmoten** [comment]
I'd like to see a link to the generator changes too.

**Comment by deepak2016** [comment]
Below is the list of pull requests in generator repo:
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/133
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/135
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/136
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/137
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/138
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/139
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/140
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/145

**Pull request merged**
