### PR TITLE
bugfix/json memory

### PR DESCRIPTION
**Pull request by baywet**
- code-gen update: getrawJson and getSerializer removal
- updates unit tests to map to new properties instead of reading raw JSON

related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/122

### CODE REVIEW

**Comment by baywet** [comment]
related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/123

**Comment by hosmanagic-axcient** [comment]
@baywet Thanks for this! Do you maybe (at least roughly) when we can expect v3 to be available and ready for production use?

**Comment by baywet** [comment]
@hosmanagic-axcient our plans is to roughly give it a month of preview. Of course that varies on two factors:
- The number of people that try the preview: the more, the shorter preview time.
- The number of issues found in the preview: the more, the longer preview time.

**Comment by hosmanagic-axcient** [comment]
Thanks for the rapid reply.: ) I guess the preview will be available soon then?

**Comment by baywet** [comment]
@hosmanagic-axcient see #628 (although is doesn't contain your changes just yet)

**Review by MIchaelMainer — APPROVED** [review]
Conditional that setRawObject is required to be public

**Comment by baywet** [comment]
@MIchaelMainer FYI I moved the toString() removal to #629 and rebased. Putting the content of 629 in here was a bad idea as it meant that both https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/122 and https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/123 needed to be merged. leading into a broken snaphot.
Sorry about that.

**Pull request merged**
