### PR TITLE
- adds missing param for serializer logger

### PR DESCRIPTION
**Pull request by baywet**
@MIchaelMainer @zengin FYI this pull reuqest was submitted from codespaces :D

### CODE REVIEW

**Review by MIchaelMainer — APPROVED** [review]
> FYI this pull reuqest was submitted from codespaces :D

I approve this with feelings of nerd jealousy

**Comment by zengin** [comment]
hey, when did we start using codespaces?

**Comment by baywet** [comment]
The button lit up for me sometime ago and the saml restriction is not a problem anymore. Try it, go to the main page of the repo and click on the green code button. You should get an option for code space

**Comment by MIchaelMainer** [comment]
Button is not lit up for me yet.

**Comment by baywet** [comment]
Did you request access? https://github.com/features/codespaces

**Pull request merged**
