### PR TITLE
[issue-511] Fix serialization of additional data on Collections

### PR DESCRIPTION
**Pull request by bougar**
This PR tries to solve #511 issue.
I just modified the `getChildAdditionalData` method in order to support the serialization of additional properties on List items.

### CODE REVIEW

**Comment by baywet** [comment]
@bougar thanks for the PR, I'll review it shortly. In the meantime, can you make sure you sign the CLA please? (see previous message)

**Review by baywet — DISMISSED** [review]

**Comment by baywet** [comment]
thanks @bougar for the pull request. I made a few modifications:
- the unit test you added was testing presence of data but not that the data was "at the right place" (we have to revamp our unit tests for that aspect as well...)
- there was a bug were the serialized data was not being added at the right level
- I did some refactoring at the method had a lot of duplicated code and was hard to read
Great job on catching the issue and starting the work to fix it!

**Comment by baywet** [comment]
BTW @bougar if you sign up here and send a few other pull requests within the month, they'll send you a cool t-shirt!
https://hacktoberfest.digitalocean.com/

**Review by MIchaelMainer — APPROVED** [review]
Reviewed via Teams. LGTM

**Pull request merged**
