### PR TITLE
Fixing import statements in java sdk test files

### PR DESCRIPTION
**Pull request by deepak2016**
### Changes proposed in this pull request
Fixes import statements for the test java files. Removes imports with * and imports specific classes. Orders import statements correctly.

### Other links
-

### CODE REVIEW

**Comment by davidmoten** [comment]
@deepak2016 I'd say go and merge this. Doesn't need further community consultation as is very minor (IMO).

**Comment by davidmoten** [comment]
Actually @deepak2016 I release this could cause work in the other PRs that would need to rebase and resolve conflicts in their imports. I'd like to see merge of existing PRs before this goes through. That way the only rebase work is in this PR and it will be trivial (just use the IDE to organise imports as I'm sure you did).

**Comment by deepak2016** [comment]
This pull request is organizing import statements in the files. Should be easy to incorporate these changes in other pull request. I'm going ahead and merging this pull request.

**Comment by davidmoten** [comment]
This is disappointing. This PR had almost zero value and now forces me to update my PRs. Please give priority to reviewing and merging existing PRs before this sort of change.

**Comment by deepak2016** [comment]
Thanks for feedback. Almost zero value is something I don't agree with. This is a step towards reducing memory footprint to build SDK and bring conformity in the way import statements are written. If you have noticed java-memory-fix branch has started passing Travis CI.

**Pull request merged**
