### PR TITLE
An attempt to cast BufferedInputStream to ProfilePhoto fails

### LINKED ISSUE #176: graphServiceClient.users(userId).photo().getContent().buildRequest().put(imageBytes) throws java.lang.ClassCastException
### Expected behavior

graphServiceClient.users(userId).photo().getContent().buildRequest().put(imageBytes) should not throw an invalid cast exception from BufferedInputStream to ProfilePhoto

### Actual behavior

java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.microsoft.graph.models.extensions.ProfilePhoto

### Steps to reproduce the behavior

graphServiceClient.users(userId).photo().getContent().buildRequest().put(imageBytes)

### PR DESCRIPTION
**Pull request by Krisoblucki-okta**
fixes #176

### CODE REVIEW

**Comment by Krisoblucki-okta** [comment]
@deepak2016 what is the review process for these?

**Comment by Krisoblucki-okta** [comment]
@deepak2016 yes, totally understand the cycle, the PR is just a fix proposal and it does address the issue.

**Comment by Krisoblucki-okta** [comment]
@deepak2016 what is eta of such things getting merged?  I need to figure out if I should make this change in my branch and roll with that or whether I should wait on you guys to make the change.

**Comment by deepak2016** [comment]
@Krisoblucki-okta we are working on the fix. This fix will have to go to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator branch, which is used to generate code used here. This should take around a week time to get fixed. We are investigating if this issue is limited to ProfilePhoto or is common with all stream classes.

**Comment by Krisoblucki-okta** [comment]
@deepak2016 thanks for the update, I'll look for v1.0.2 then

**Comment by Krisoblucki-okta** [comment]
@deepak2016 @NakulSabharwal wondering if this ended up being addressed already?

**Comment by baywet** [comment]
Hi @Krisoblucki-okta 
Thanks for submitting this PR and thank you for your patience.
After solving the conflicts of the pull request, it appears it didn't solve the original issue.
I've authored PR #454 which solves the issue. This PR will be closed when the PR I authored gets merged.
Sorry we couldn't get your PR merged.

**Pull request closed without merging**
