### PR TITLE
Fixing import statments for request extension classes

### PR DESCRIPTION
**Pull request by deepak2016**
Fixes #
This results in memory gain of 2.5GB. Java SDK after this change builds with 7.5Gb RAM instead of taking more than 10GB

### Changes proposed in this pull request
Fix import statements for all request extension classes in java sdk

### Other links
-

### CODE REVIEW

**Comment by davidmoten** [comment]
See also #44

**Comment by davidmoten** [comment]
From #44:
>An easy option is after pasting generated code, use an IDE like Eclipse to organize imports across the project (right mouse on project - Source - Organize imports).

This might save you a lot of trouble in 3.

**Comment by deepak2016** [comment]
Yes, this is good idea, I totally agree with this approach. But we plan to automate SDK refresh process, hence planning to invest in fixing template files.

**Comment by deepak2016** [comment]
I have tried that, java sdk builds with 1GB RAM, if I organize import for entire project.

**Comment by davidmoten** [comment]
That's great! I don't mind organize imports being applied now on the project (I'll fix my PRs) because it will enable CI and allow general public to build the project (not everyone has 11GB on their machine!). I guess it depends on how long it takes to fix the templates.

**Comment by deepak2016** [comment]
We are planning to be in a state to run Travis CI without issue by end of the month.

**Pull request merged**
