### PR TITLE
Update generated files with build 90185

### PR DESCRIPTION
**Pull request by ramsessanchez**
Superseding #1243 using  https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/857
This addresses https://github.com/microsoftgraph/msgraph-sdk-java/issues/1063

### CODE REVIEW

**Comment by ramsessanchez** [comment]
Still needs changelog

**Comment by baywet** [comment]
@ramsessanchez good catch! This is most likely caused by [this change in the metadata](https://github.com/microsoftgraph/msgraph-metadata/pull/213). Reports are a bit all over the place metadata wise, let me confirm this is expected.

**Comment by baywet** [comment]
After looking into it further it seems that all the getXXX reports make sense for that change. However, there are a few reports that are still on the older format (all the ones not starting with get). Trying to get a confirmation on whether these will align too from @darrelmiller . https://learn.microsoft.com/en-us/graph/api/intune-deviceconfig-reportroot-deviceconfigurationuseractivity?view=graph-rest-1.0
@irvinesunday do you think we could tweak the filter to only include what starts with "get" if those reports are not going to align on the service side?

**Comment by baywet** [comment]
see this article as well https://devblogs.microsoft.com/microsoft365dev/changes-to-microsoft-365-apps-usage-reports-api-in-microsoft-graph/

**Comment by irvinesunday** [comment]
> After looking into it further it seems that all the getXXX reports make sense for that change. However, there are a few reports that are still on the older format (all the ones not starting with get). Trying to get a confirmation on whether these will align too from @darrelmiller . https://learn.microsoft.com/en-us/graph/api/intune-deviceconfig-reportroot-deviceconfigurationuseractivity?view=graph-rest-1.0 @irvinesunday do you think we could tweak the filter to only include what starts with "get" if those reports are not going to align on the service side?

Created an issue to track this: https://github.com/microsoftgraph/msgraph-metadata/issues/216

**Comment by baywet** [comment]
Thanks. Bottom line I don't think we should release this version since it breaks things that are working today on top of fixing broken things. Thoughts @darrelmiller @andrueastman (and everyone on this thread)?

**Comment by irvinesunday** [comment]
Here's a PR resolving that @baywet: https://github.com/microsoftgraph/msgraph-metadata/pull/217

**Comment by baywet** [comment]
thanks, closing this one, we'll trigger a new generation.

**Pull request closed without merging**
