### PR TITLE
Generated  models and request builders

### PR DESCRIPTION
**Pull request by andrueastman**
This pull request was automatically created by Azure Pipelines. **Important** Check for unexpected deletions or changes in this PR.

### CODE REVIEW

**Comment by ramsessanchez** [comment]
@baywet Reason for closing? This pr is for the the kiota generated library.

**Comment by baywet** [comment]
@ramsessanchez we somehow had two PRs open from the same branch, look at #1423 it's the same thing.

**Comment by ramsessanchez** [comment]
@baywet A bit confused here, this pr is from the kiota/v1.0/pipelineBuild/# branch whereas the other is the v1.0/pipelinebuild/# branch.

**Comment by baywet** [comment]
My bad. Thanks for calling this out, please go ahead and reopen the pr

**Review by ramsessanchez — DISMISSED** [review]

**Review by ramsessanchez — APPROVED** [review]

**Pull request merged**
