### PR TITLE
Generated models and request builders using Typewriter   Pay special attention to the deletions when reviewing this.

### PR DESCRIPTION
**Pull request by MIchaelMainer**

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
@NakulSabharwal and @deepak2016 this builds locally for me. Can you  help me understand why this isn't completing with CI build?

**Comment by deepak2016** [comment]
looking into it.

**Comment by deepak2016** [comment]
- I was able to build branch v1.0/pipelinebuild/859585 locally
- Started custom build in Travis and build failed as there was no output for 10 minutes
I'm investigating why travis build is taking too long.

**Comment by deepak2016** [comment]
local build completed in 7 minutes

**Comment by deepak2016** [comment]
We have not fixed extension folder, as there are not lot of changes there.
We have fixed around 25 templates out of 40 templates which have maximum impact in build time and memory impact. So not all the files have fixed import statements.

One reason can be that there are lots of addition in extension folder, which may be causing increase in time. Investigating more.

**Comment by deepak2016** [comment]
Closing old pull request.

**Pull request closed without merging**
